# Generated by Django 6.0.6 on 2026-07-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_blockedip_auditlog_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('TOKEN_BLACKLISTED', 'Token Blacklisted'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('PERMISSION_DENIED', 'Permission Denied')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPARTMENT', 'Department'), ('AUTH', 'Authentication')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
