# Generated by Django 6.0.6 on 2026-07-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_add_extra_action_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPARTMENT', 'Department'), ('AUTH', 'Authentication')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
