# Generated by Django 6.0.6 on 2026-07-09 05:08

import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_manager_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/aadhaar/', validators=[documents.validators.validate_pdf, documents.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/pan/', validators=[documents.validators.validate_pdf, documents.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', validators=[documents.validators.validate_image, documents.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employees/resumes/', validators=[documents.validators.validate_pdf, documents.validators.validate_file_size]),
        ),
    ]
