# Generated by Django 6.0.6 on 2026-07-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the employee.'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo.', null=True, upload_to='employee_profiles/'),
        ),
    ]
