# Generated by Django 6.0.6 on 2026-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeprofile_bio_employeeprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
