"""
Django settings for company_portal project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
SECRET_KEY = "django-insecure-ec_)j%)h^ipc9rj^!i66h)bqa=f$g0==m&k8a(!_#8p8ldbb2p"

DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # Project Apps
    "employees",
    "accounts",
    "api",
    "audit_logs",

    # Third-Party Apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_yasg",

    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "middleware.performance.PerformanceLoggingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Custom Middleware
    "employees.middleware.RequestLoggingMiddleware",
    "employees.middleware.ResponseTimeMiddleware",
    "employees.middleware.IPRestrictionMiddleware",
]

ROOT_URLCONF = "company_portal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "company_portal.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "company_portal",
        "USER": "postgres",
        "PASSWORD": "mysql",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = "/static/"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"


# ═══════════════════════════════════════════════════════════════
# Django REST Framework Configuration
# ═══════════════════════════════════════════════════════════════
REST_FRAMEWORK = {
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # Permissions — require authentication by default
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Filters
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

    # Throttling (Module 7)
    "DEFAULT_THROTTLE_CLASSES": [
        "api.throttling.StandardUserThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/min",
        "login": "5/min",       # Auth: 5 requests/minute
        "employee": "100/min",  # Employee API: 100 requests/minute
        "report": "20/min",     # Report API: 20 requests/minute
    },

    # Global Exception Handler (Module 4)
    "EXCEPTION_HANDLER": "api.exceptions.custom_exception_handler.custom_exception_handler",
}


# ═══════════════════════════════════════════════════════════════
# Simple JWT Configuration (Module 10 — Security)
# ═══════════════════════════════════════════════════════════════
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ═══════════════════════════════════════════════════════════════
# Caching Configuration (Performance Module)
# ═══════════════════════════════════════════════════════════════
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "company-portal-cache",
        "TIMEOUT": 300,  # 5 minutes default
    }
}


# ═══════════════════════════════════════════════════════════════
# Security Settings (Module 10)
# ═══════════════════════════════════════════════════════════════
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_BROWSER_XSS_FILTER = True

import os

# ═══════════════════════════════════════════════════════════════
# Logging Configuration (Merged — application + performance)
# ═══════════════════════════════════════════════════════════════
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {module} — {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "performance": {
            "format": "[{asctime}] {levelname} — {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "application_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "application.log",
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "error.log",
            "formatter": "verbose",
        },
        "security_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "security.log",
            "formatter": "verbose",
        },
        "request_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "request.log",
            "formatter": "verbose",
        },
        "performance_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "performance.log",
            "formatter": "performance",
        },
    },

    "loggers": {
        "application": {
            "handlers": ["console", "application_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "security": {
            "handlers": ["console", "security_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "request": {
            "handlers": ["request_file"],
            "level": "INFO",
            "propagate": False,
        },
        "performance": {
            "handlers": ["console", "performance_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",
            "propagate": True,
        },
    },
}


# ==========================================================
# Session Configuration (Performance Module)
# ==========================================================

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 1800          # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False      # Change to True in production (HTTPS)
SESSION_COOKIE_SAMESITE = "Lax"